theme: jekyll-theme-minimal
logo: ./figures/Chris.jpeg
title: Yiming Wang's HomePage
description: Thanks for visiting my homepage and welcome to contact me at:<br /><br /><a href="mailto:wym12416@pku.edu.com">📮 wym12416@pku.edu.com</a><br />